//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Oracle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Oracle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankDB {
            get {
                object obj = ResourceManager.GetObject("BlankDB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy &quot;C:\My Solutions\The Oracle\bin\Debug\The Oracle.exe&quot; &quot;C:\Oracle\&quot;
        ///copy &quot;C:\My Solutions\The Oracle\bin\Debug\The Oracle.exe&quot; &quot;C:\Oracle SS\&quot;
        ///copy &quot;C:\My Solutions\The Oracle\bin\Debug\The Oracle.exe&quot; &quot;D:\Oracle\&quot;
        ///copy &quot;C:\My Solutions\The Oracle\bin\Debug\The Oracle.exe&quot; &quot;D:\Oracle LC\&quot;.
        /// </summary>
        internal static string CopyOracle {
            get {
                return ResourceManager.GetString("CopyOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OracleDatabase&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;15&lt;/UserID&gt;
        ///    &lt;UserName&gt;David Jones&lt;/UserName&gt;
        ///	&lt;Color&gt;#FFA0B392&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;16&lt;/UserID&gt;
        ///    &lt;UserName&gt;Steven Fletcher&lt;/UserName&gt;
        ///	&lt;Color&gt;#FF71B1D9&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;17&lt;/UserID&gt;
        ///    &lt;UserName&gt;Steven Sutton&lt;/UserName&gt;
        ///	&lt;Color&gt;#FFAED8F2&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;18&lt;/UserID&gt;
        ///    &lt;UserName&gt;Tracey Morgan&lt;/UserName&gt;
        ///	&lt;Color&gt;#FFF2DEA2&lt;/Color&gt;
        ///  &lt;/Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OracleDatabaseSettingsXML {
            get {
                return ResourceManager.GetString("OracleDatabaseSettingsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Oracle&gt;
        ///  &lt;Settings&gt;
        ///    &lt;UserID&gt;15&lt;/UserID&gt;
        ///    &lt;UserName&gt;David Jones&lt;/UserName&gt;
        ///    &lt;DatabaseLocation&gt;N:\OracleData&lt;/DatabaseLocation&gt;
        ///    &lt;HoverDatabaseLocation&gt;N:\HoverData&lt;/HoverDatabaseLocation&gt;
        ///  &lt;/Settings&gt;
        ///&lt;/Oracle&gt;.
        /// </summary>
        internal static string OracleSettingsXML {
            get {
                return ResourceManager.GetString("OracleSettingsXML", resourceCulture);
            }
        }
    }
}
