//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_Oracle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("The_Oracle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echo on
        ///echo &quot;Copying Event Horizon.exe to Users Folders&quot;
        ///copy &quot;C:\My Solutions\Event Horizon\bin\Debug\Event Horizon.exe&quot; &quot;C:\Oracle Bill Gates\&quot;
        ///copy &quot;C:\My Solutions\Event Horizon\bin\Debug\Event Horizon.exe&quot; &quot;C:\Oracle Mark Zuckerberg\&quot;
        ///copy &quot;C:\My Solutions\Event Horizon\bin\Debug\Event Horizon.exe&quot; &quot;D:\Oracle Elon Musk\&quot;
        ///copy &quot;C:\My Solutions\Event Horizon\bin\Debug\Event Horizon.exe&quot; &quot;D:\Oracle Steve Jobs\&quot;
        ///copy &quot;C:\My Solutions\Event Horizon\bin\Debug\Event Horizon.exe&quot; &quot;D:\Oracle Steve Waznia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopyEventHorizon {
            get {
                return ResourceManager.GetString("CopyEventHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--Event Horizon local settings file generated by the program.--&gt;
        ///&lt;EventHorizon&gt;
        ///  &lt;Settings&gt;
        ///    &lt;UserName&gt;David Jones&lt;/UserName&gt;
        ///    &lt;DatabaseLocation&gt;D:\EventHorizonRemoteDatabase&lt;/DatabaseLocation&gt;
        ///  &lt;/Settings&gt;
        ///&lt;/EventHorizon&gt;.
        /// </summary>
        internal static string EventHorizonLocalSettings {
            get {
                return ResourceManager.GetString("EventHorizonLocalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EventHorizonRemoteDatabase {
            get {
                object obj = ResourceManager.GetObject("EventHorizonRemoteDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;EventHorizonDatabase&gt;
        ///  
        ///  &lt;Users&gt;
        ///	&lt;UserName&gt;David Jones&lt;/UserName&gt;
        ///	&lt;Color&gt;#FFA0B392&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;2&lt;/UserID&gt;
        ///    &lt;UserName&gt;Bill Gates&lt;/UserName&gt;
        ///	&lt;Color&gt;#FF71B1D9&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;3&lt;/UserID&gt;
        ///    &lt;UserName&gt;Steve Jobs&lt;/UserName&gt;
        ///	&lt;Color&gt;#FFAED8F2&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;4&lt;/UserID&gt;
        ///    &lt;UserName&gt;Elon Musk&lt;/UserName&gt;
        ///	&lt;Color&gt;#FFF2DEA2&lt;/Color&gt;
        ///  &lt;/Users&gt;
        ///  &lt;Users&gt;
        ///    &lt;UserID&gt;5&lt;/U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventHorizonRemoteSettings {
            get {
                return ResourceManager.GetString("EventHorizonRemoteSettings", resourceCulture);
            }
        }
    }
}
